swagger: '2.0'
host: '127.0.0.1:8989'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag

paths:
  /srv1/abon/all:
    get:
      summary: output hello world.
      produces:
        - application/text
      responses:
        '200':
          description: OK
          schema:
            example: "Bulk page!!!"
      tags:
        - default
