swagger: '2.0'
host: '127.0.0.1:8080'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag

paths:
  /srv1/auth/login:
    post:
      summary: User login
  /srv1/admin/adduser:
    post:
      summary: Add new user
  /srv1/abon/all:
    get:
      summary: Show all abonents in database
      parameters:
        - name: req_data
          required: True
          description: JSON Web Token
      produces:
        - application/text
      responses:
        '200':
          description: OK
          schema:
            example: "{status: 'success', \ntext: 'Authorized request',\nall_abon:{...}\n}"
      tags:
        - default
  /srv1/call/sample:
    post:
      summary: Demo Call
