swagger: '2.0'
host: '127.0.0.1:8080'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: python-swagger-ui test api
  description: python-swagger-ui test api
tags:
  - name: default
    description: default tag

paths:
  /srv1/auth/login:
    post:
      summary: Login Test
  /srv1/admin/adduser:
    post:
      summary: Adduser Test
  /srv1/abon/all:
    get:
      summary: Abonents Test
      produces:
        - application/text
      responses:
        '200':
          description: OK
          schema:
            example: "Bulk page!!!"
      tags:
        - default
  /srv1/call/sample:
    post:
      summary: Call Test
